kind: "RoleBinding"
apiVersion: "rbac.authorization.k8s.io/v1"
metadata:
  name: "qs-sb2-camel-rhosak"
roleRef:
  # Add the "namespace-reader" role to the service account
  kind: "Role"
  name: "namespace-reader"
subjects:
  - kind: "ServiceAccount"
    name: "qs-sb2-camel-rhosak"
